name: Deploy To-Do App to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

permissions:
  contents: write  # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload files
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'  # upload everything in the repo

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
